# Generated by Django 3.2.25 on 2025-03-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off-duty', 'Off-duty'), ('idle', 'Idle'), ('in-transit', 'In Transit'), ('assigned', 'Assigned'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_Order.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_notes', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('pickup', 'Pick-Up'), ('dropoff', 'Drop-Off')], max_length=50)),
                ('completion_time', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in-transit', 'In Transit'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='unassigned', max_length=20)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_Order.team')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_Order.technician')),
            ],
        ),
    ]
