# Generated by Django 3.2.25 on 2025-03-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='details',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recipient_notes',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_completion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_completion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recipient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Client_Order.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Client_Order.technician'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
