# Generated by Django 3.2.25 on 2025-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_Order', '0004_auto_20250304_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='name',
            field=models.CharField(default='Unknown Technician', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('off_duty', 'Off Duty'), ('available', 'Available'), ('on_mission', 'On Mission')], default='off_duty', max_length=20),
        ),
    ]
